# Generated by Django 5.0.2 on 2024-03-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'participant'), (2, 'researcher')], default=False),
        ),
    ]
