# Generated by Django 5.0.2 on 2024-03-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_account_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('study_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('study_name', models.CharField(max_length=255)),
                ('user_id', models.PositiveSmallIntegerField(choices=[(1, 'participant'), (2, 'researcher')], default=False)),
                ('irb_pdf', models.CharField(max_length=255)),
                ('pre_study_questionnaire', models.CharField(max_length=255)),
                ('questions_list', models.JSONField()),
                ('post_study_questionnaire', models.CharField(max_length=255)),
            ],
        ),
    ]
