# Generated by Django 5.0.2 on 2024-03-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='irb_pdf',
            field=models.FileField(upload_to=''),
        ),
    ]
