# Generated by Django 5.0.2 on 2024-03-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_study_irb_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='irb_pdf',
            field=models.FileField(upload_to='irb_pdfs/'),
        ),
    ]
