# Generated by Django 5.0.2 on 2024-03-13 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_study_irb_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyData',
            fields=[
                ('response_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False) ),
                ('study_id', models.PositiveSmallIntegerField(default=False)),
                ('user_id', models.PositiveSmallIntegerField(choices=[(1, 'participant'), (2, 'researcher')], default=False)),
                ('irb_pdf_signature', models.CharField(max_length=255)),
                ('pre_study_questionnaire_filled', models.BooleanField()),
                ('questions_answers_list', models.JSONField()),
                ('post_study_questionnaire_filled', models.BooleanField()),
                ('study_completed', models.BooleanField()),
            ],
        ),
    ]
