# Generated by Django 5.0.2 on 2024-03-14 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_studydata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studydata',
            name='study_id',
            field=models.PositiveSmallIntegerField(default=False),
        ),
    ]
