# Generated by Django 5.0.2 on 2024-03-14 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_studydata_post_study_questionnaire_filled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studydata',
            name='questions_answers_list',
            field=models.JSONField(null=True),
        ),
    ]
