# Generated by Django 5.0.2 on 2024-03-17 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_studydata_study_id'),
        ('users', '0007_studydata_study_id'),
        ('users', '0008_alter_studydata_questions_answers_list'),
    ]

    operations = [
    ]
